# LiteLLM Proxy Configuration

model_list:
  - model_name: groq-primary
    litellm_params:
      model: meta-llama/llama-4-scout-17b-16e-instruct
      api_key: os.environ/GROQ_API_KEY
      api_base: https://api.groq.com/openai/v1
      custom_llm_provider: openai

litellm_settings:
  callbacks: ["mlflow"]
  log_level: DEBUG

callback_settings:
  mlflow:
    experiment_name: "llmops-new"